name: Run test and deploy
on: push 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: pull code
        uses: actions/checkout@v3
      - name: install deps
        run: npm ci
      - name: testing
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: pull code
        uses: actions/checkout@v3
      - name: install deps
        run: npm ci
      - name: build
        run: npm run build
      - name: deploy
        run:  echo "deploying"